Feature/zolder regel implementatie
WoonstadRotterdamTemp/woningwaardering pull request #14
Opened 2024-04-09 18:59 UTC by tiddoloos

2024-04-09 20:17 UTC, benverhees requested changes

2024-04-10 15:08 UTC, tiddoloos commented on tests/stelsels/zelfstandige_woonruimten/oppervlakte_van_overige_ruimten/test_OppervlakteVanOverigeRuimten
yep was rename  van de file -> er miste .py

2024-04-10 15:08 UTC, tiddoloos commented on tests/stelsels/zelfstandige_woonruimten/oppervlakte_van_vertrekken/modellen/output/peildatum/2024-01-01/zolder_vertrek.json
done

2024-04-10 19:06 UTC, benverhees approved these changes

2024-04-10 19:49 UTC, merged