Feature/tms 118 max punten verwarming
WoonstadRotterdamTemp/woningwaardering pull request #25
Opened 2024-04-22 13:25 UTC by tiddoloos

implementatie voor het berekenen van de punten voor verwarming.
TODO: check wanneer de ruimte verwarmd is en meetelt voor de punten voor Verwarming

2024-04-22 13:58 UTC, benverhees commented
Klopt het dat hier nog geen maximering per ruimte in zit?

2024-04-22 14:16 UTC, tiddoloos commented
> Klopt het dat hier nog geen maximering per ruimte in zit?

besproken en is dus niet nodig

2024-04-22 14:50 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +                and ruimte.soort.code is not None
duplicate met hierboven?

2024-04-22 16:00 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +                and ruimte.soort.code is not None
is nodig voor mypy

2024-04-22 19:51 UTC, benverhees requested changes

2024-04-22 19:51 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
De functie `vertrek_telt_als_vertrek` is alleen geschikt om te bepalen of een vertrek als vertrek gezien mag worden, niet om onderscheid te maken tussen vertrekken en overige ruimten. Nu wordt alles wat gespecifceerd is als overige ruimte en verwarmd meegerekend, terwijl er overige ruimten zijn die niet gewaardeerd mogen worden, zoals toiletruimte, hallen, overlopen, entree, schachten etc.

2024-04-22 20:42 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
Klopt!

2024-04-23 06:06 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
je hebt gelijk, we moeten in de for loop beginnen met een filter op detailsoort net als in oppervlakte van overige ruimten. dat ga ik toevoegen. maar volgens mij als je alleen geldige overige ruimten en vertrekken doorlaat dan kan je deze functie wel degelijk op deze manier gebruiken. de eerste check in deze functie is namelijk:
```
if ruimte.soort.code != Ruimtesoort.vertrek.code:
            return False
```
zo gebruiken we hem ook in oppervlakte van overige ruimten.

2024-04-23 06:32 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +                and ruimte.soort.code is not None
Niet meer omdat je na de nieuwe changes errors raised!

2024-04-23 06:36 UTC, sTomerG commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
ja als je alleen op geldige overige ruimten daarvoor hebt gefilterd zou het wel werken

2024-04-23 06:47 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
Het voelt gewoon ook wat gek dat we `if not vertrek_telt_als_vertrek` doen, en dan in die statement overige ruimten gaan waarderen.
Ik denk dat we beter `if vertrek_telt_als_vertrek` kunnen doen, daarin vertrekken waarderen, en dan apart overige ruimten waarderen. Nu worden volgens mij alle vertrekken en alle overige ruimten die verwarmd zijn gewaardeerd.

2024-04-23 06:57 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
het zit hem dan meer in de naamgeving denk ik. je wil de punten beinvloeden wanneer je te maken hebt met een overige ruimte. daarom wil je ook voor een vertrek weten of het een overige ruimte is. daarom is dit denk ik niet zo gek om zo te doen.

2024-04-23 06:58 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
fuctie zou je kunnen noemen: `ruimte_telt_als_verterk`?

2024-04-23 07:06 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
Misschien zie ik het verkeerd, maar ook als we de naamgeving aanpassen kunnen we hem toch nog steeds niet gebruiken om te bepalen of een overige ruimte gewaardeerd mag worden?

2024-04-23 07:08 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
Je zegt "je wilt de punten beinvloeden wanneer je te maken hebt met een overige ruimte", maar je wilt toch ook alleen vertrekken waarderen wanneer een vertrek in aanmerking komt om gewaardeerd te worden? Of komt dat niet voor?

2024-04-23 07:20 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
Stel dat ik (foutief) een toiletruimte als vertrek instuur, dan wordt ie nu als overige ruimte gerekend, toch?

2024-04-23 07:43 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
volgens miji niet want dat vang je af met dit (wat ik nog moet committen):
```
...in [
                    Ruimtedetailsoort.bijkeuken.code,
                    Ruimtedetailsoort.berging.code,
                    Ruimtedetailsoort.wasruimte.code,
                    Ruimtedetailsoort.garage.code,
                    Ruimtedetailsoort.zolder.code,
                    Ruimtedetailsoort.kelder.code,
                    Ruimtedetailsoort.parkeerplaats.code,
                    # Deze vertrekken kunnen als overige ruimte tellen
                    # wanneer ze niet aan bepaalde voorwaarden voldoen:
                    Ruimtedetailsoort.woonkamer.code,
                    Ruimtedetailsoort.woon_en_of_slaapkamer.code,
                    Ruimtedetailsoort.woonkamer_en_of_keuken.code,
                    Ruimtedetailsoort.keuken.code,
                    Ruimtedetailsoort.overig_vertrek.code,
                    Ruimtedetailsoort.badkamer.code,
                    Ruimtedetailsoort.badkamer_met_toilet.code,
                    Ruimtedetailsoort.doucheruimte.code,
                    Ruimtedetailsoort.zolder.code,
                    Ruimtedetailsoort.slaapkamer.code,
                ]
```

dus hoe deze PR nu is werkt het idd nog niet zoals het moet

2024-04-23 07:48 UTC, benverhees commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +            if not vertrek_telt_als_vertrek(ruimte):
Misschien goed om dat ook in de utils te stoppen dan?

2024-04-23 12:09 UTC, tiddoloos commented on woningwaardering/stelsels/zelfstandige_woonruimten/verwarming/verwarming_2024.py
> +                and ruimte.soort.code is not None
klopt

2024-04-24 15:54 UTC, benverhees submitted a review, later dismissed

2024-04-25 09:43 UTC, benverhees submitted a review, later dismissed

2024-04-25 10:29 UTC, benverhees approved these changes

2024-04-25 10:34 UTC, merged