tms 92: project setup readme
WoonstadRotterdamTemp/woningwaardering pull request #4
Opened 2024-03-07 14:41 UTC by tiddoloos

Eerste aanzet voor een readme met daarin principes en bronnen voor de woningwaardering berekening, naamconventies en package design.

2024-03-11 10:57 UTC, sTomerG requested changes
Ziet er goed uit! Paar kleine suggesties

2024-03-11 10:57 UTC, sTomerG commented on README.md
> +Referentiedata:WONINGWAARDERINGSTELSELGROEP - CORA VERA online, Woningcorporatie Referentiearchitectuur.
```suggestion
```

2024-03-11 10:57 UTC, sTomerG commented on README.md
> +### Referentie Data
```suggestion
### Referentiedata
```

2024-03-11 10:57 UTC, sTomerG commented on README.md
> +Ook wanneer een wet verandert met ingang op een bepaalde datum zorgt de modulariteit ervoor dat de juiste regels worden gebruikt voor de stelselgroep.
```suggestion
Ook wanneer een wet verandert met ingang van een bepaalde datum zorgt de modulariteit ervoor dat de juiste regels worden gebruikt voor de stelselgroep.
```

2024-03-11 10:57 UTC, sTomerG commented on docs/afbeeldingen/project_design.excalidraw
Ik zou deze file *oppervlakte_van_vertrekken.excalidraw* noemen zodat het duidelijk is voor welke png deze file de bron is

2024-03-11 12:13 UTC, sTomerG submitted a review, later dismissed

2024-03-18 11:09 UTC, benverhees commented
Ik zou in de voorbeelden waar we data definieren begindatum en einddatum gebruiken ipv peildatum. Peildatum wordt gebruikt voor de input, om te bepalen welke waarden/functies we gebruiken op basis van de begindatum en einddatum

2024-03-19 17:09 UTC, sTomerG commented on README.md
> +Mochten er daardoor meerdere rijen geldig zijn voor een peildatum, dan gaat de `woningwaardering`-package uit van de bovenste rij als geldig.
Of gaan we toch voor een error zoals besproken vandaag?

2024-03-19 17:09 UTC, sTomerG commented on README.md
> +In de `woningwaardering`-package wordt namelijk een peildatum gebruikt om de juiste waarde van bijvoorbeeld een variabele uit een tabel te selecteren.
```suggestion
In de `woningwaardering`-package wordt een peildatum gebruikt om de juiste waarde van bijvoorbeeld een variabele uit een tabel te selecteren.
```

2024-03-20 08:35 UTC, tiddoloos commented on README.md
> +Mochten er daardoor meerdere rijen geldig zijn voor een peildatum, dan gaat de `woningwaardering`-package uit van de bovenste rij als geldig.
Ik heb nu geschreven dat we een error geven. maar dit betekent wel dat de package dus onbruikbaar wordt voor een bepaalde peildatum of request (afhankelijk van waar de dubbele rijen gevonden worden)

2024-03-20 15:57 UTC, benverhees approved these changes

2024-03-20 15:58 UTC, merged